AllCops:
  Exclude:
      - vendor/**/*
      - Gemfile*
      - '*.gemspec' # This does nothing. Why?
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 150

# Gemspec/RequireMFA:
#   enable: false
