AllCops:
  Exclude:
      - vendor/**/*
      - Gemfile*
      - '*.gemspec' # This does nothing. Why?
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/HashAlignment:
  disable

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/CommandLiteral:
  EnforcedStyle: percent_x

# Gemspec/RequireMFA:
#   enable: false
