AllCops:
  Exclude:
      - vendor/**/*
      - Gemfile*
      - '*.gemspec' # This does nothing. Why?
  NewCops: enable

Layout/HashAlignment:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/CommandLiteral:
  EnforcedStyle: percent_x

# Gemspec/RequireMFA:
#   enable: false
